# Generated by Django 5.2.1 on 2025-05-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
