# Generated by Django 5.2.1 on 2025-05-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
